//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Runtime.Serialization.Formatters.Binary;
using System.IO;
using System;
using AgentApp.Models;
using AgentDB.Models;
using System.Collections.Generic;

namespace AccommodationService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="AccommodationService.AccommodationPort")]
    public interface AccommodationPort
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.updateAccommodationResponse1> updateAccommodationAsync(AccommodationService.updateAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.deleteAccommodationResponse1> deleteAccommodationAsync(AccommodationService.deleteAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.addAccommodationResponse1> addAccommodationAsync(AccommodationService.addAccommodationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.getAccommodationTypesResponse> getAccommodationTypesAsync(AccommodationService.getAccommodationTypesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.getAdditionalServicesResponse> getAdditionalServicesAsync(AccommodationService.getAdditionalServicesRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AccommodationService.getAccommodationResponse1> getAccommodationAsync(AccommodationService.getAccommodationRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class updateAccommodationRequest
    {
        
        private AccommodationDTO accommodationDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccommodationDTO AccommodationDTO
        {
            get
            {
                return this.accommodationDTOField;
            }
            set
            {
                this.accommodationDTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class AccommodationDTO
    {     
        private long idField;
        
        private AccommodationType accommodationTypeField;
        
        private int categoryField;
        
        private AdditionalService[] additionalServiceField;
        
        private bool freeCancellationField;
        
        private int cancellationDaysField;
        
        private decimal cancellationPriceField;
        
        private string descriptionField;
        
        private string[] imagesField;
        
        private int numberOfPersonsField;
        
        private long agentIdField;
        
        private decimal defaultPriceField;
        
        private PeriodPrice[] periodPriceField;
        
        private Location locationField;
        
        private Unavailability[] unavailabilityField;
        
        private long[] reservationIdsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public AccommodationType AccommodationType
        {
            get
            {
                return this.accommodationTypeField;
            }
            set
            {
                this.accommodationTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public int category
        {
            get
            {
                return this.categoryField;
            }
            set
            {
                this.categoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("AdditionalService", Namespace="")]
        public AdditionalService[] AdditionalService
        {
            get
            {
                return this.additionalServiceField;
            }
            set
            {
                this.additionalServiceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public bool freeCancellation
        {
            get
            {
                return this.freeCancellationField;
            }
            set
            {
                this.freeCancellationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public int cancellationDays
        {
            get
            {
                return this.cancellationDaysField;
            }
            set
            {
                this.cancellationDaysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal cancellationPrice
        {
            get
            {
                return this.cancellationPriceField;
            }
            set
            {
                this.cancellationPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("images")]
        public string[] images
        {
            get
            {
                return this.imagesField;
            }
            set
            {
                this.imagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public int numberOfPersons
        {
            get
            {
                return this.numberOfPersonsField;
            }
            set
            {
                this.numberOfPersonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public long agentId
        {
            get
            {
                return this.agentIdField;
            }
            set
            {
                this.agentIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal defaultPrice
        {
            get
            {
                return this.defaultPriceField;
            }
            set
            {
                this.defaultPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("PeriodPrice", Namespace="")]
        public PeriodPrice[] PeriodPrice
        {
            get
            {
                return this.periodPriceField;
            }
            set
            {
                this.periodPriceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="")]
        public Location Location
        {
            get
            {
                return this.locationField;
            }
            set
            {
                this.locationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Unavailability", Namespace="")]
        public Unavailability[] Unavailability
        {
            get
            {
                return this.unavailabilityField;
            }
            set
            {
                this.unavailabilityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("reservationIds")]
        public long[] reservationIds
        {
            get
            {
                return this.reservationIdsField;
            }
            set
            {
                this.reservationIdsField = value;
            }
        }

        //neka public metoda
        public Accommodation CreateAccommodation()
        {
            Accommodation acc = new Accommodation();

            acc.Id = this.idField;

            if(this.accommodationTypeField != null)
            {
                acc.AccommodationType = this.accommodationTypeField.CreateAccommodationType();
            }
            acc.Category = this.category;
            if(this.additionalServiceField != null)
            {
                List<AgentApp.Models.AdditionalService> addServices = new List<AgentApp.Models.AdditionalService>();
                for (int i = 0; i < this.additionalServiceField.Length; ++i)
                {
                    addServices.Add(this.additionalServiceField[i].CreateAdditionalService());
                }
                acc.AdditionalServices = addServices;
            }
            acc.FreeCancellation = this.freeCancellationField;
            acc.CancellationDays = this.cancellationDaysField;
            acc.Description = this.descriptionField;
            acc.Images = this.imagesField;
            acc.NumberOfPersons = this.numberOfPersonsField;
            acc.DefaultPrice = this.defaultPriceField;
            if(this.periodPriceField != null)
            {
                List<AgentApp.Models.PeriodPrice> prdPrices = new List<AgentApp.Models.PeriodPrice>();
                for (int i = 0; i < this.periodPriceField.Length; ++i)
                {
                    prdPrices.Add(this.periodPriceField[i].CreatePeriodPrice());
                }
                acc.PeriodPrices = prdPrices;
            }
            if(this.locationField != null)
            {
                acc.Location = this.locationField.CreateLocation();
            }
            if (this.unavailabilityField != null)
            {
                List<AgentApp.Models.Unavailability> unvs = new List<AgentApp.Models.Unavailability>();
                for (int i = 0; i < unavailabilityField.Length; ++i)
                {
                    unvs.Add(this.unavailabilityField[i].CreateUnavailability());
                }
                acc.Unavailabilities = unvs;
            }
            if(this.reservationIdsField != null)
            {
                List<ReservationLong> resIds = new List<ReservationLong>();
                for (int i = 0; i < reservationIdsField.Length; ++i)
                {
                    ReservationLong reservationLong = new ReservationLong();
                    reservationLong.Value = this.reservationIdsField[i];
                    resIds.Add(reservationLong);
                }
                acc.ReservationIds = resIds;
            }

            return acc;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class AccommodationType
    {
        
        private string typeNameField;
        private long id;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string typeName
        {
            get
            {
                return this.typeNameField;
            }
            set
            {
                this.typeNameField = value;
            }
        }

        public long Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        public AgentApp.Models.AccommodationType CreateAccommodationType()
        {
            AgentApp.Models.AccommodationType accType = new AgentApp.Models.AccommodationType();
            accType.TypeName = this.typeName;
            accType.Id = this.id;
            return accType;
        }

    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "")]
    public partial class AdditionalService
    {

        private string additionalServiceNameField;
        private long id;

        public long Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string additionalServiceName
        {
            get
            {
                return this.additionalServiceNameField;
            }
            set
            {
                this.additionalServiceNameField = value;
            }
        }

        public AgentApp.Models.AdditionalService CreateAdditionalService()
        {
            AgentApp.Models.AdditionalService addService = new AgentApp.Models.AdditionalService();
            addService.Id = this.id;
            addService.AdditionalServiceName = this.additionalServiceNameField;

            return addService;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class PeriodPrice
    {

        private long id;

        private System.DateTime startDateField;
        
        private System.DateTime endDateField;
        
        private decimal priceField;

        public long Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal price
        {
            get
            {
                return this.priceField;
            }
            set
            {
                this.priceField = value;
            }
        }

        public AgentApp.Models.PeriodPrice CreatePeriodPrice()
        {
            AgentApp.Models.PeriodPrice perPrice = new AgentApp.Models.PeriodPrice();
            perPrice.Id = this.id;
            perPrice.Price = this.price;
            perPrice.StartDate = this.startDate;
            perPrice.EndDate = this.endDate;

            return perPrice;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class Location
    {
        private long id;

        private string countryField;
        
        private string cityField;
        
        private string addressField;
        
        private decimal latitudeField;
        
        private decimal longitudeField;
        
        public Location()
        {
            this.latitudeField = ((decimal)(0.0m));
            this.longitudeField = ((decimal)(0.0m));
        }
        
        public long Id
        {
            get
            {
                return this.id;
            }
            set
            {
                this.id = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string city
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public string address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal latitude
        {
            get
            {
                return this.latitudeField;
            }
            set
            {
                this.latitudeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute()]
        public decimal longitude
        {
            get
            {
                return this.longitudeField;
            }
            set
            {
                this.longitudeField = value;
            }
        }

        public AgentApp.Models.Location CreateLocation()
        {
            AgentApp.Models.Location loc = new AgentApp.Models.Location();
            loc.Id = this.id;
            loc.Address = this.addressField;
            loc.City = this.cityField;
            loc.Country = this.countryField;
            loc.Latitude = this.latitude;
            loc.Longitude = this.longitude;

            return loc;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class Unavailability
    {
        private long idField;

        private System.DateTime startDateField;
        
        private System.DateTime endDateField;

        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        public AgentApp.Models.Unavailability CreateUnavailability()
        {
            AgentApp.Models.Unavailability unav = new AgentApp.Models.Unavailability();
            unav.Id = this.idField;
            unav.StartDate = this.startDate;
            unav.EndDate = this.endDate;

            return unav;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class updateAccommodationResponse
    {
        
        private AccommodationDTO accommodationDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccommodationDTO AccommodationDTO
        {
            get
            {
                return this.accommodationDTOField;
            }
            set
            {
                this.accommodationDTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccommodationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.updateAccommodationRequest updateAccommodationRequest;
        
        public updateAccommodationRequest1()
        {
        }
        
        public updateAccommodationRequest1(AccommodationService.updateAccommodationRequest updateAccommodationRequest)
        {
            this.updateAccommodationRequest = updateAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateAccommodationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.updateAccommodationResponse updateAccommodationResponse;
        
        public updateAccommodationResponse1()
        {
        }
        
        public updateAccommodationResponse1(AccommodationService.updateAccommodationResponse updateAccommodationResponse)
        {
            this.updateAccommodationResponse = updateAccommodationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class deleteAccommodationRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class deleteAccommodationResponse
    {
        
        private bool flagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool flag
        {
            get
            {
                return this.flagField;
            }
            set
            {
                this.flagField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAccommodationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.deleteAccommodationRequest deleteAccommodationRequest;
        
        public deleteAccommodationRequest1()
        {
        }
        
        public deleteAccommodationRequest1(AccommodationService.deleteAccommodationRequest deleteAccommodationRequest)
        {
            this.deleteAccommodationRequest = deleteAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class deleteAccommodationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.deleteAccommodationResponse deleteAccommodationResponse;
        
        public deleteAccommodationResponse1()
        {
        }
        
        public deleteAccommodationResponse1(AccommodationService.deleteAccommodationResponse deleteAccommodationResponse)
        {
            this.deleteAccommodationResponse = deleteAccommodationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class addAccommodationRequest
    {
        
        private AccommodationDTO accommodationDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccommodationDTO AccommodationDTO
        {
            get
            {
                return this.accommodationDTOField;
            }
            set
            {
                this.accommodationDTOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class addAccommodationResponse
    {
        
        private AccommodationDTO accommodationDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccommodationDTO AccommodationDTO
        {
            get
            {
                return this.accommodationDTOField;
            }
            set
            {
                this.accommodationDTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.addAccommodationRequest addAccommodationRequest;
        
        public addAccommodationRequest1()
        {
        }
        
        public addAccommodationRequest1(AccommodationService.addAccommodationRequest addAccommodationRequest)
        {
            this.addAccommodationRequest = addAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addAccommodationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.addAccommodationResponse addAccommodationResponse;
        
        public addAccommodationResponse1()
        {
        }
        
        public addAccommodationResponse1(AccommodationService.addAccommodationResponse addAccommodationResponse)
        {
            this.addAccommodationResponse = addAccommodationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class getAccommodationTypesRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationTypesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.getAccommodationTypesRequest getAccommodationTypesRequest;
        
        public getAccommodationTypesRequest1()
        {
        }
        
        public getAccommodationTypesRequest1(AccommodationService.getAccommodationTypesRequest getAccommodationTypesRequest)
        {
            this.getAccommodationTypesRequest = getAccommodationTypesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationTypesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAccommodationTypesResponse", Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AccommodationType", Namespace="", IsNullable=false)]
        public AccommodationService.AccommodationType[] getAccommodationTypesResponse1;
        
        public getAccommodationTypesResponse()
        {
        }
        
        public getAccommodationTypesResponse(AccommodationService.AccommodationType[] getAccommodationTypesResponse1)
        {
            this.getAccommodationTypesResponse1 = getAccommodationTypesResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class getAdditionalServicesRequest
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAdditionalServicesRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.getAdditionalServicesRequest getAdditionalServicesRequest;
        
        public getAdditionalServicesRequest1()
        {
        }
        
        public getAdditionalServicesRequest1(AccommodationService.getAdditionalServicesRequest getAdditionalServicesRequest)
        {
            this.getAdditionalServicesRequest = getAdditionalServicesRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAdditionalServicesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getAdditionalServicesResponse", Namespace="", Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AdditionalService", Namespace="", IsNullable=false)]
        public AccommodationService.AdditionalService[] getAdditionalServicesResponse1;
        
        public getAdditionalServicesResponse()
        {
        }
        
        public getAdditionalServicesResponse(AccommodationService.AdditionalService[] getAdditionalServicesResponse1)
        {
            this.getAdditionalServicesResponse1 = getAdditionalServicesResponse1;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class getAccommodationRequest
    {
        
        private long idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="")]
    public partial class getAccommodationResponse
    {
        
        private AccommodationDTO accommodationDTOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AccommodationDTO AccommodationDTO
        {
            get
            {
                return this.accommodationDTOField;
            }
            set
            {
                this.accommodationDTOField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.getAccommodationRequest getAccommodationRequest;
        
        public getAccommodationRequest1()
        {
        }
        
        public getAccommodationRequest1(AccommodationService.getAccommodationRequest getAccommodationRequest)
        {
            this.getAccommodationRequest = getAccommodationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getAccommodationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public AccommodationService.getAccommodationResponse getAccommodationResponse;
        
        public getAccommodationResponse1()
        {
        }
        
        public getAccommodationResponse1(AccommodationService.getAccommodationResponse getAccommodationResponse)
        {
            this.getAccommodationResponse = getAccommodationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public interface AccommodationPortChannel : AccommodationService.AccommodationPort, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "1.0.0.1")]
    public partial class AccommodationPortClient : System.ServiceModel.ClientBase<AccommodationService.AccommodationPort>, AccommodationService.AccommodationPort
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AccommodationPortClient() : 
                base(AccommodationPortClient.GetDefaultBinding(), AccommodationPortClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AccommodationPortSoap11.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccommodationPortClient(EndpointConfiguration endpointConfiguration) : 
                base(AccommodationPortClient.GetBindingForEndpoint(endpointConfiguration), AccommodationPortClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccommodationPortClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AccommodationPortClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccommodationPortClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AccommodationPortClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AccommodationPortClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.updateAccommodationResponse1> AccommodationService.AccommodationPort.updateAccommodationAsync(AccommodationService.updateAccommodationRequest1 request)
        {
            return base.Channel.updateAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.updateAccommodationResponse1> updateAccommodationAsync(AccommodationService.updateAccommodationRequest updateAccommodationRequest)
        {
            AccommodationService.updateAccommodationRequest1 inValue = new AccommodationService.updateAccommodationRequest1();
            inValue.updateAccommodationRequest = updateAccommodationRequest;
            return ((AccommodationService.AccommodationPort)(this)).updateAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.deleteAccommodationResponse1> AccommodationService.AccommodationPort.deleteAccommodationAsync(AccommodationService.deleteAccommodationRequest1 request)
        {
            return base.Channel.deleteAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.deleteAccommodationResponse1> deleteAccommodationAsync(AccommodationService.deleteAccommodationRequest deleteAccommodationRequest)
        {
            AccommodationService.deleteAccommodationRequest1 inValue = new AccommodationService.deleteAccommodationRequest1();
            inValue.deleteAccommodationRequest = deleteAccommodationRequest;
            return ((AccommodationService.AccommodationPort)(this)).deleteAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.addAccommodationResponse1> AccommodationService.AccommodationPort.addAccommodationAsync(AccommodationService.addAccommodationRequest1 request)
        {
            return base.Channel.addAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.addAccommodationResponse1> addAccommodationAsync(AccommodationService.addAccommodationRequest addAccommodationRequest)
        {
            AccommodationService.addAccommodationRequest1 inValue = new AccommodationService.addAccommodationRequest1();
            inValue.addAccommodationRequest = addAccommodationRequest;
            return ((AccommodationService.AccommodationPort)(this)).addAccommodationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.getAccommodationTypesResponse> AccommodationService.AccommodationPort.getAccommodationTypesAsync(AccommodationService.getAccommodationTypesRequest1 request)
        {
            return base.Channel.getAccommodationTypesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.getAccommodationTypesResponse> getAccommodationTypesAsync(AccommodationService.getAccommodationTypesRequest getAccommodationTypesRequest)
        {
            AccommodationService.getAccommodationTypesRequest1 inValue = new AccommodationService.getAccommodationTypesRequest1();
            inValue.getAccommodationTypesRequest = getAccommodationTypesRequest;
            return ((AccommodationService.AccommodationPort)(this)).getAccommodationTypesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.getAdditionalServicesResponse> AccommodationService.AccommodationPort.getAdditionalServicesAsync(AccommodationService.getAdditionalServicesRequest1 request)
        {
            return base.Channel.getAdditionalServicesAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.getAdditionalServicesResponse> getAdditionalServicesAsync(AccommodationService.getAdditionalServicesRequest getAdditionalServicesRequest)
        {
            AccommodationService.getAdditionalServicesRequest1 inValue = new AccommodationService.getAdditionalServicesRequest1();
            inValue.getAdditionalServicesRequest = getAdditionalServicesRequest;
            return ((AccommodationService.AccommodationPort)(this)).getAdditionalServicesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AccommodationService.getAccommodationResponse1> AccommodationService.AccommodationPort.getAccommodationAsync(AccommodationService.getAccommodationRequest1 request)
        {
            return base.Channel.getAccommodationAsync(request);
        }
        
        public System.Threading.Tasks.Task<AccommodationService.getAccommodationResponse1> getAccommodationAsync(AccommodationService.getAccommodationRequest getAccommodationRequest)
        {
            AccommodationService.getAccommodationRequest1 inValue = new AccommodationService.getAccommodationRequest1();
            inValue.getAccommodationRequest = getAccommodationRequest;
            return ((AccommodationService.AccommodationPort)(this)).getAccommodationAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccommodationPortSoap11))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AccommodationPortSoap11))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8081/ws");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AccommodationPortClient.GetBindingForEndpoint(EndpointConfiguration.AccommodationPortSoap11);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AccommodationPortClient.GetEndpointAddress(EndpointConfiguration.AccommodationPortSoap11);
        }
        
        public enum EndpointConfiguration
        {
            
            AccommodationPortSoap11,
        }
    }
}
